from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, ValidationError
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from agentic_rag.config import Settings
from agentic_rag.models.json_llm import JsonLLMError, extract_json_object
from agentic_rag.models.providers import OpenAICompatibleClient, ProviderError


class ImageVLMError(RuntimeError):
    """Raised when image VLM caption generation fails."""


SceneType = Literal["chart", "diagram", "screenshot", "photo", "document", "unknown"]


class ImageObjectDescription(BaseModel):
    """Single local object/region description from an image VLM."""

    label: str = ""
    description: str = ""
    confidence: float = 0.0


class ImageVLMDescription(BaseModel):
    """Structured image description generated by a VLM."""

    caption: str = ""
    scene_type: SceneType = "unknown"
    visible_text_summary: str = ""
    objects: list[ImageObjectDescription] = Field(default_factory=list)
    confidence: float = 0.0


class ImageVLMClient:
    """OpenAI-compatible VLM client for image caption/object extraction."""

    MIME_MAP = {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".jp2": "image/jp2",
        ".webp": "image/webp",
        ".bmp": "image/bmp",
        ".gif": "image/gif",
    }

    def __init__(self, settings: Settings):
        self.settings = settings
        self.client = OpenAICompatibleClient(
            base_url=settings.image_vlm_base_url,
            api_key=settings.image_vlm_api_key,
            timeout=settings.image_vlm_timeout_sec,
        )

    def describe_image(self, image_path: str | Path) -> ImageVLMDescription:
        """Generate a structured semantic description for a local image."""

        retry_call = retry(
            reraise=True,
            stop=stop_after_attempt(self.settings.image_vlm_max_retries),
            wait=wait_exponential(multiplier=1, min=1, max=6),
            retry=retry_if_exception_type((ProviderError, ImageVLMError)),
        )(self._describe_once)
        return retry_call(Path(image_path))

    def _describe_once(self, image_path: Path) -> ImageVLMDescription:
        data_url = self._image_to_data_url(image_path)
        payload: dict[str, Any] = {
            "model": self.settings.image_vlm_model,
            "stream": False,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": (
                                "请分析这张图片，只输出 JSON，不要输出 Markdown。"
                                "字段必须包含 caption, scene_type, visible_text_summary, objects, confidence。"
                                "objects 是对象数组，每项包含 label, description, confidence。"
                                "不要生成最终问答答案，只描述图片中的可见内容、文字和关键对象。"
                            ),
                        },
                        {"type": "image_url", "image_url": {"url": data_url}},
                    ],
                }
            ],
        }
        if self.settings.image_vlm_enable_thinking:
            payload["extra_body"] = {"enable_thinking": True}
        data = self.client.post("chat/completions", payload)
        content = self._extract_content(data)
        try:
            raw = extract_json_object(content)
            return ImageVLMDescription.model_validate(raw)
        except (JsonLLMError, ValidationError) as exc:
            raise ImageVLMError(f"Image VLM JSON validation failed: {exc}") from exc

    def _image_to_data_url(self, image_path: Path) -> str:
        if not image_path.exists():
            raise ImageVLMError(f"Image file not found: {image_path}")
        mime = self.MIME_MAP.get(image_path.suffix.lower(), "application/octet-stream")
        try:
            encoded = base64.b64encode(image_path.read_bytes()).decode("utf-8")
        except Exception as exc:
            raise ImageVLMError(f"Failed to read image file {image_path}: {exc}") from exc
        return f"data:{mime};base64,{encoded}"

    @staticmethod
    def _extract_content(data: dict[str, Any]) -> str:
        choices = data.get("choices")
        if not isinstance(choices, list) or not choices:
            raise ImageVLMError("Image VLM response missing choices")
        message = choices[0].get("message") if isinstance(choices[0], dict) else None
        if not isinstance(message, dict):
            raise ImageVLMError("Image VLM response missing message")
        content = message.get("content")
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            return "\n".join(
                str(item.get("text") or item.get("content") or "")
                for item in content
                if isinstance(item, dict)
            )
        raise ImageVLMError("Image VLM response missing text content")


def image_vlm_description_to_json(description: ImageVLMDescription) -> str:
    """Return compact JSON for metadata/debug output."""

    return json.dumps(description.model_dump(), ensure_ascii=False, separators=(",", ":"))
